//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSLR_DeliveryMessagingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomMessage
    {
        public int ID { get; set; }
        public string CustomMessage1 { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<int> MessageStatus { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
