//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSLR_DeliveryMessagingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSLR_MasterEntities1 : DbContext
    {
        public TSLR_MasterEntities1()
            : base("name=TSLR_MasterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CustomMessage> CustomMessages { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
    }
}
